### ISSUE TITLE
Should I use this library or Ecsy for a new project?

### ISSUE THREAD

**Issue by DouglasDev** [DavidPeicho/ecstra#13]
It seems that the Ecsy repo is dead at this point whereas this library is being updated regularly. On the other hand, Ecsy already has a decent number of features as well as bindings to many other libraries and dev tools. I'm working on an experimental game that will probably requiring swapping out large sections of the codebase in the future since there's certain features of my project that I'm still unsure on how they will work or if they will work. So I'm looking for a library that will provide maximum architectural flexibility but I don't need it to have tons of features. I realize that neither project has reached a stable release, but how complete would you say this library is compared to Ecsy? Thanks!

**Comment by DavidPeicho** [comment]
Hey! Thanks for posting that. I would still say Ecsy has more "features" and may be a bit more stable. Ecstra is super close to Ecsy. I decided to make it because I am actually using Ecsy at work and I needed to easily be able to fix bug or improve performance.

What Ecsy does better:
* Might be more stable?
* Deferred removal of component and entity
* Has StateComponent logic
* Has reactive queries
* Has a chrome extension
* Has a better doc

What Ecstra does better:
* Typescript first class support
* System topological ordering
* Component inheritance merging (might not be that useful but still nice)

I am 100% willing to drive this library further, but this will be mostly on my free time (even though I use it at work). I agree with what you said regarding features / tooling / stability. I would prefer having a stable and easy to use library with some good tooling even if it misses some features.

I can't exactly answer your question, but if you go with Ecstra and you need improvement we can work it out.

I haven't finished my roadmap but it's likely to be:

* Add benchmarks to avoid performance regression
* Figure out if deferred adding / removal is necessary, and maybe implement it. It could be totally different from Ecsy and use command buffers like Unity
* Figure out if StateComponent are needed and look if we can do something similar / better
* Find a nice way to implement reactive queries

Browser debugging extension / profiling has less priority IMO because it's easy enough to use the chrome inspector for now.

**Comment by DouglasDev** [comment]
Thanks for such a detailed reply! I guess I'll start out with Ecsy and then switch to your library later on if I encounter issues with it. Hope your boss gives you some extra time to work on this since it looks very promising and there's really no complete ECS for JavaScript.
